# Generated by Django 5.2.6 on 2025-09-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_alerte', models.CharField(choices=[('incendie', 'Incendie'), ('inondation', 'Inondation'), ('ordures', 'Ordures bouchées'), ('vol', 'Vol'), ('autre', 'Autre')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='nouvelle', max_length=20)),
            ],
        ),
    ]
