# Generated by Django 5.2.6 on 2025-11-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type_alerte', models.CharField(choices=[('incendie', 'Incendie'), ('inondation', 'Inondation'), ('vol', 'Vol'), ('autre', 'Autre')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('adresse', models.CharField(blank=True, max_length=300, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='alertes_photos/')),
            ],
        ),
    ]
