# Generated by Django 5.2.6 on 2025-11-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=20),
        ),
    ]
