# Generated by Django 5.2.6 on 2025-09-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('incendie', 'Incendie'), ('inondation', 'Inondation'), ('vol', 'Vol'), ('autre', 'Autre')], max_length=20),
        ),
    ]
