# Generated by Django 5.2.6 on 2025-09-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_alerte_type_alerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='adresse',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
