# Generated by Django 5.2.6 on 2025-10-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alerte_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerte',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='titre',
        ),
    ]
