# Generated by Django 5.2.6 on 2025-10-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alter_alerte_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
