# Generated by Django 5.2.6 on 2025-10-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alerte_latitude_alerte_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='alertes_photos/'),
        ),
    ]
